apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa-order-service.yaml
  - hpa-procurement-service.yaml
  - hpa-quality-service.yaml
  - hpa-quotation-service.yaml
  - hpa-inventory-service.yaml
  - hpa-supplier-service.yaml
  - hpa-logistics-service.yaml  