apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa-ingress-controller.yaml
  - hpa-auth-service.yaml
  - hpa-bff-marketing.yaml
  - hpa-bff-talents.yaml
  - hpa-bff-production.yaml
  - hpa-notification-service.yaml
  - hpa-analytics-service.yaml