"use client";
import { useState } from 'react';
import { callApi, callGraphQL } from '../components/api';
export default function Page() {
  const [email, setEmail] = useState('marketer@example.com');
  const [password, setPassword] = useState('Password123!');
  const [token, setToken] = useState('');
  const [output, setOutput] = useState('Marketing app — REST at /api/marketing/*, GraphQL at /api/marketing/graphql');
  async function register() { const data = await callApi('/auth/register', 'POST', { name: 'Marketing User', email, password, roles: ['marketing'] }); setToken(data.token); setOutput(JSON.stringify(data, null, 2)); }
  async function login() { const data = await callApi('/auth/login', 'POST', { email, password }); setToken(data.token); setOutput(JSON.stringify(data, null, 2)); }
  async function dashboard() { const data = await callApi('/marketing/dashboard', 'GET', undefined, token); setOutput(JSON.stringify(data, null, 2)); }
  async function workflow() { const data = await callApi('/marketing/workflows/lead-engagement', 'POST', { lead: { company: 'Agency Assist JP', personName: 'Minh Tuan', email: 'minh_tuan@gmail.com', fit: 88, intent: 84, urgency: 75, channel: 'webinar', tags: ['decision-maker'], landingPage: '/events/backend-modernization' }, engagement: { clicks: 2, visits: 3, pricingVisits: 2 }, expectedDeal: 22000 }, token); setOutput(JSON.stringify(data, null, 2)); }
  async function createCampaign() { const data = await callApi('/marketing/campaign/campaigns', 'POST', { payload: { name: 'Q2 Growth Sprint', subject: 'Backend modernization webinar follow-up', budget: 18000, targetLeads: 240, targetListId: 'webinar-hot', templateCode: 'follow-up-01' } }, token); setOutput(JSON.stringify(data, null, 2)); }
  async function gqlDashboard() { const data = await callGraphQL('{ dashboard }', undefined, token); setOutput(JSON.stringify(data, null, 2)); }
  async function gqlLeadEngagement() { const data = await callGraphQL('mutation($input: LeadEngagementInput!) { leadEngagement(input: $input) }', { input: { lead: { company: 'Agency Assist JP', personName: 'Minh Tuan', email: 'minh_tuan@gmail.com', fit: 88, intent: 84, urgency: 75, channel: 'webinar', tags: ['decision-maker'], landingPage: '/events/backend-modernization' }, engagement: { clicks: 2, visits: 3, pricingVisits: 2 }, expectedDeal: 22000 } }, token); setOutput(JSON.stringify(data, null, 2)); }
  async function gqlLaunchCampaign() { const data = await callGraphQL('mutation($id: String!) { launchCampaign(campaignId: $id) }', { id: 'campaign-001' }, token); setOutput(JSON.stringify(data, null, 2)); }
  return (<main className="container"><section className="hero"><span className="badge">Marketing App (Next.js)</span><h1>Marketing Automation Console</h1><p>Dual-mode BFF: REST via <code>/api/marketing/*</code>, GraphQL via <code>/api/marketing/graphql</code>.</p></section><section className="grid two" style={{ marginTop: 20 }}><div className="card"><div>Email</div><input value={email} onChange={(e) => setEmail(e.target.value)} /><div style={{marginTop:12}}>Password</div><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} /><div className="row" style={{marginTop:14}}><button onClick={register}>Register</button><button className="secondary" onClick={login}>Login</button><button className="secondary" onClick={dashboard} disabled={!token}>Dashboard (REST)</button><button className="secondary" onClick={createCampaign} disabled={!token}>Create campaign (REST)</button><button className="secondary" onClick={workflow} disabled={!token}>Lead engagement (REST)</button></div><div className="row" style={{marginTop:8}}><button className="secondary" onClick={gqlDashboard} disabled={!token}>Dashboard (GraphQL)</button><button className="secondary" onClick={gqlLeadEngagement} disabled={!token}>Lead engagement (GraphQL)</button><button className="secondary" onClick={gqlLaunchCampaign} disabled={!token}>Launch campaign (GraphQL)</button></div></div><div className="card"><div className="code">{output}</div></div></section></main>);
}
