apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - campaign-service.yaml
  - hot-lead-service.yaml
  - leads-acquisition-service.yaml
  - scoring-service.yaml
  - tracking-service.yaml