apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa-campaign-service.yaml
  - hpa-hot-lead-service.yaml
  - hpa-leads-acquisition-service.yaml
  - hpa-scoring-service.yaml
  - hpa-tracking-service.yaml