apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: explore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
        monitoring: enabled
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '7002'
    spec:
      containers:
      - name: analytics-service
        image: analytics-service:version3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7002
        env:
        - name: PORT
          value: '7002'
        - name: POSTGRES_HOST
          value: 172.19.0.5
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: analytics_service
        - name: KAFKA_ENABLED
          value: 'true'
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: host.docker.internal:9092
        - name: KAFKA_EVENTS_TOPIC
          value: explore.events
        - name: KAFKA_CONSUMER_GROUP
          value: analytics-service-group
        - name: ELASTICSEARCH_URL
          value: http://172.19.0.1:9200
        - name: ELASTICSEARCH_EVENTS_INDEX
          value: explore-events-v3
        - name: ELASTICSEARCH_PROJECTION_INDEX
          value: explore-projections-v3
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: explore
  labels:
    app: analytics-service
    monitoring: enabled
spec:
  selector:
    app: analytics-service
  ports:
  - name: http
    port: 7002
    targetPort: 7002
