apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - analytics-service.yaml
  - cost-service.yaml
  - invoice-service.yaml
  - payment-service.yaml
  - revenue-service.yaml
  - payroll-service.yaml