apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa-recruitment-service.yaml
  - hpa-employees-service.yaml
  - hpa-training-service.yaml
  - hpa-motivation-service.yaml