apiVersion: apps/v1
kind: Deployment
metadata:
  name: motivation-service
  namespace: explore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motivation-service
  template:
    metadata:
      labels:
        app: motivation-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "7144"
    spec:
      containers:
        - name: motivation-service
          image: motivation-service:version3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7144
          env:
            - name: REDIS_URL
              value: "redis://172.19.0.6:6379/0"
            - name: REDIS_PREFIX
              value: "motivation-service"
            - name: DEFAULT_CACHE_TTL_SECONDS
              value: "600"
            - name: PORT
              value: "7144"
            - name: POSTGRES_HOST
              value: "172.19.0.1"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "motivation_service"
            - name: KAFKA_ENABLED
              value: "true"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "172.19.0.1:9092"
            - name: KAFKA_EVENTS_TOPIC
              value: "explore.events"
---
apiVersion: v1
kind: Service
metadata:
  name: motivation-service
  namespace: explore
spec:
  selector:
    app: motivation-service
  ports:
    - name: http
      port: 7144
      targetPort: 7144
